# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/MyProjects/Projects/SG/Nov5/SG/hw/hw.srcs/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_1/system_mipi_csi2_rx_subsyst_0_1.xci
# IP: The module: 'system_mipi_csi2_rx_subsyst_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/MyProjects/Projects/SG/Nov5/SG/hw/hw.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_1/bd_0/bd_e207.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_e207 || ORIG_REF_NAME==bd_e207} -quiet] -quiet

# IP: d:/MyProjects/Projects/SG/Nov5/SG/hw/hw.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_0/bd_e207_r_sync_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_e207_r_sync_0 || ORIG_REF_NAME==bd_e207_r_sync_0} -quiet] -quiet

# IP: d:/MyProjects/Projects/SG/Nov5/SG/hw/hw.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_1/bd_e207_rx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_e207_rx_0 || ORIG_REF_NAME==bd_e207_rx_0} -quiet] -quiet

# IP: d:/MyProjects/Projects/SG/Nov5/SG/hw/hw.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_2/bd_e207_phy_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_e207_phy_0 || ORIG_REF_NAME==bd_e207_phy_0} -quiet] -quiet

# IP: d:/MyProjects/Projects/SG/Nov5/SG/hw/hw.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_3/bd_e207_vfb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_e207_vfb_0_0 || ORIG_REF_NAME==bd_e207_vfb_0_0} -quiet] -quiet

# XDC: d:/MyProjects/Projects/SG/Nov5/SG/hw/hw.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_1/bd_0/bd_e207_ooc.xdc

# XDC: d:/MyProjects/Projects/SG/Nov5/SG/hw/hw.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_1/system_mipi_csi2_rx_subsyst_0_1_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_mipi_csi2_rx_subsyst_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/MyProjects/Projects/SG/Nov5/SG/hw/hw.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_1/system_mipi_csi2_rx_subsyst_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_mipi_csi2_rx_subsyst_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/MyProjects/Projects/SG/Nov5/SG/hw/hw.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_1/system_mipi_csi2_rx_subsyst_0_1_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_mipi_csi2_rx_subsyst_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/MyProjects/Projects/SG/Nov5/SG/hw/hw.srcs/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_1/system_mipi_csi2_rx_subsyst_0_1.xci
# IP: The module: 'system_mipi_csi2_rx_subsyst_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/MyProjects/Projects/SG/Nov5/SG/hw/hw.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_1/bd_0/bd_e207.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_e207 || ORIG_REF_NAME==bd_e207} -quiet] -quiet

# IP: d:/MyProjects/Projects/SG/Nov5/SG/hw/hw.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_0/bd_e207_r_sync_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_e207_r_sync_0 || ORIG_REF_NAME==bd_e207_r_sync_0} -quiet] -quiet

# IP: d:/MyProjects/Projects/SG/Nov5/SG/hw/hw.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_1/bd_e207_rx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_e207_rx_0 || ORIG_REF_NAME==bd_e207_rx_0} -quiet] -quiet

# IP: d:/MyProjects/Projects/SG/Nov5/SG/hw/hw.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_2/bd_e207_phy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_e207_phy_0 || ORIG_REF_NAME==bd_e207_phy_0} -quiet] -quiet

# IP: d:/MyProjects/Projects/SG/Nov5/SG/hw/hw.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_1/bd_0/ip/ip_3/bd_e207_vfb_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_e207_vfb_0_0 || ORIG_REF_NAME==bd_e207_vfb_0_0} -quiet] -quiet

# XDC: d:/MyProjects/Projects/SG/Nov5/SG/hw/hw.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_1/bd_0/bd_e207_ooc.xdc

# XDC: d:/MyProjects/Projects/SG/Nov5/SG/hw/hw.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_1/system_mipi_csi2_rx_subsyst_0_1_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_mipi_csi2_rx_subsyst_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/MyProjects/Projects/SG/Nov5/SG/hw/hw.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_1/system_mipi_csi2_rx_subsyst_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_mipi_csi2_rx_subsyst_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/MyProjects/Projects/SG/Nov5/SG/hw/hw.gen/sources_1/bd/system/ip/system_mipi_csi2_rx_subsyst_0_1/system_mipi_csi2_rx_subsyst_0_1_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_mipi_csi2_rx_subsyst_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
